import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "../components/Button";
import SvgComponent from "../components/Icons/Login";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://nextjs.org">Devter</a>
        </h1>
        <p className={styles.text}>Bienvenido a la comunidad Dev</p>
        <Button>
          <SvgComponent fill="#fff" />
          Login
        </Button>
        {/* <nav>
          <Link href="/timeline">
            <a>Timeline</a>
          </Link>
        </nav> */}
      </main>
    </div>
  );
}
